options:
  maas-url:
    type: string
    description: "Mass API Endpoint.  ex: http://10.0.0.10/MAAS"
  maas-oauth:
    type: string
    description: "Mass oauth credentials. From user 'account' page."
  vms:
    type: string
    description: "Number of vms to create.  Default: 2"
